"""Render the generated compatibility matrix."""

from __future__ import annotations

from pathlib import Path

from .spec import load_categories, load_entries, load_spec_module


OUT_PATH = Path("docs/compatibility/compatibility-matrix.md")


def render_matrix() -> str:
    module = load_spec_module()
    categories = load_categories()
    entries = load_entries()
    display = module.STATUS_DISPLAY
    lines = [
        "<!-- Generated by wolfppt-harness matrix. Do not edit by hand. -->",
        "",
        "# WolfPPT Compatibility Matrix",
        "",
        "This matrix is generated from `docs/compatibility/_compat_spec.py`.",
        "",
    ]
    for category in categories:
        category_entries = [entry for entry in entries if entry["category"] == category["id"]]
        if not category_entries:
            continue
        lines.extend(
            [
                f"## {category['title']}",
                "",
                "| id | priority | status | capability | oracle | notes |",
                "|---|---:|---|---|---|---|",
            ]
        )
        for entry in category_entries:
            notes = entry.get("notes", "")
            if entry.get("gap_id"):
                notes = f"{notes} Gap: `{entry['gap_id']}`.".strip()
            lines.append(
                "| {id} | {priority} | {status} | {capability} | {oracle} | {notes} |".format(
                    id=f"`{entry['id']}`",
                    priority=entry["priority"],
                    status=display[entry["status"]],
                    capability=_escape(entry["capability"]),
                    oracle=_escape(entry["oracle"]),
                    notes=_escape(notes),
                )
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_matrix(path: str | Path = OUT_PATH) -> Path:
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_matrix(), encoding="utf-8")
    return out


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")

