"""State inspection helpers for presentation saves."""

from __future__ import annotations

from typing import Any


_PENDING_EDIT_FIELDS = (
    "_slide_creations",
    "_slide_deletions",
    "_slide_order",
    "_slide_layout_removals",
    "_notes_slide_adds",
    "_part_placeholder_adds",
    "_shape_adds",
    "_shape_deletes",
    "_group_child_shape_deletes",
    "_table_cell_edits",
    "_table_row_column_edits",
    "_table_row_height_edits",
    "_table_column_width_edits",
    "_table_cell_margin_edits",
    "_table_cell_vertical_anchor_edits",
    "_table_cell_text_frame_margin_edits",
    "_table_cell_text_frame_vertical_anchor_edits",
    "_table_cell_text_frame_content_edits",
    "_table_cell_text_frame_word_wrap_edits",
    "_table_cell_text_frame_auto_size_edits",
    "_table_cell_text_frame_fit_edits",
    "_table_cell_text_frame_paragraph_alignment_edits",
    "_table_cell_text_frame_paragraph_level_edits",
    "_table_cell_text_frame_paragraph_spacing_edits",
    "_table_cell_text_frame_paragraph_font_edits",
    "_table_cell_text_frame_paragraph_run_edits",
    "_table_cell_text_frame_paragraph_line_break_edits",
    "_table_cell_text_frame_paragraph_run_font_edits",
    "_table_cell_text_frame_paragraph_run_hyperlink_edits",
    "_table_cell_fill_solid_edits",
    "_table_cell_fill_background_edits",
    "_table_cell_fill_pattern_edits",
    "_table_cell_fill_pattern_fore_color_edits",
    "_table_cell_fill_pattern_back_color_edits",
    "_table_cell_fill_color_edits",
    "_table_cell_fill_gradient_edits",
    "_background_fill_solid_edits",
    "_background_fill_background_edits",
    "_background_fill_color_edits",
    "_table_cell_merge_edits",
    "_table_style_edits",
    "_text_run_edits",
    "_text_run_bold_edits",
    "_text_run_italic_edits",
    "_text_run_underline_edits",
    "_text_run_font_size_edits",
    "_text_run_font_name_edits",
    "_text_run_font_color_edits",
    "_text_run_font_fill_type_edits",
    "_text_run_font_language_edits",
    "_text_run_hyperlink_edits",
    "_text_run_appends",
    "_paragraph_text_edits",
    "_paragraph_clear_edits",
    "_paragraph_line_break_edits",
    "_paragraph_appends",
    "_paragraph_alignment_edits",
    "_paragraph_level_edits",
    "_paragraph_spacing_edits",
    "_paragraph_font_edits",
    "_text_frame_margin_edits",
    "_text_frame_word_wrap_edits",
    "_text_frame_vertical_anchor_edits",
    "_text_frame_auto_size_edits",
    "_text_frame_fit_edits",
    "_group_child_text_frame_margin_edits",
    "_group_child_text_frame_word_wrap_edits",
    "_group_child_text_frame_vertical_anchor_edits",
    "_group_child_text_frame_auto_size_edits",
    "_group_child_text_frame_fit_edits",
    "_shape_text_edits",
    "_group_child_text_edits",
    "_nested_group_child_text_edits",
    "_deeper_group_child_text_edits",
    "_group_child_paragraph_text_edits",
    "_group_child_paragraph_clear_edits",
    "_group_child_paragraph_line_break_edits",
    "_group_child_run_text_edits",
    "_group_child_run_font_edits",
    "_group_child_run_hyperlink_edits",
    "_group_child_paragraph_alignment_edits",
    "_group_child_paragraph_font_edits",
    "_group_child_paragraph_level_edits",
    "_group_child_paragraph_spacing_edits",
    "_part_shape_text_edits",
    "_part_paragraph_alignment_edits",
    "_part_paragraph_level_edits",
    "_part_paragraph_spacing_edits",
    "_part_paragraph_font_edits",
    "_part_run_font_edits",
    "_part_run_hyperlink_edits",
    "_part_shape_hyperlink_edits",
    "_part_text_frame_margin_edits",
    "_part_text_frame_word_wrap_edits",
    "_part_text_frame_vertical_anchor_edits",
    "_part_text_frame_auto_size_edits",
    "_shape_geometry_edits",
    "_group_child_geometry_edits",
    "_nested_group_child_geometry_edits",
    "_deeper_group_child_geometry_edits",
    "_shape_fill_solid_edits",
    "_shape_fill_background_edits",
    "_shape_fill_pattern_edits",
    "_shape_fill_pattern_fore_color_edits",
    "_shape_fill_pattern_back_color_edits",
    "_shape_fill_color_edits",
    "_shape_fill_gradient_edits",
    "_shape_line_solid_edits",
    "_shape_line_background_edits",
    "_shape_line_pattern_edits",
    "_shape_line_pattern_fore_color_edits",
    "_shape_line_pattern_back_color_edits",
    "_shape_line_color_edits",
    "_shape_line_width_edits",
    "_shape_line_dash_edits",
    "_connector_connection_edits",
    "_shape_shadow_inherit_edits",
    "_shape_hyperlink_edits",
    "_shape_target_slide_edits",
    "_shape_rotation_edits",
    "_shape_name_edits",
    "_shape_adjustment_edits",
    "_shape_line_element_edits",
    "_picture_crop_edits",
    "_picture_replace_edits",
    "_chart_data_edits",
    "_chart_title_edits",
    "_chart_legend_edits",
    "_chart_font_edits",
    "_chart_data_label_edits",
    "_chart_plot_property_edits",
    "_chart_axis_title_edits",
    "_chart_axis_property_edits",
    "_chart_style_edits",
    "_presentation_size_edits",
    "_slide_name_edits",
)


def has_pending_save_edits(presentation: Any) -> bool:
    """Return whether save needs to rewrite anything beyond copying the source."""
    if presentation._core_properties_edits is not None:
        return True
    return any(getattr(presentation, field) for field in _PENDING_EDIT_FIELDS)
