"""Python API entries for the WolfPPT compatibility spec."""

from __future__ import annotations

from _compat_spec_types import Entry


PYTHON_API_ENTRIES: list[Entry] = [
    {
        "id": "python_api.presentation_open_save",
        "category": "python_api",
        "capability": "Create blank presentations, open existing decks from paths or readable file-like objects, iterate slides and shapes, and save to paths or writable file-like outputs",
        "priority": "P0",
        "status": "supported",
        "oracle": "unit tests + python-pptx parity probe + package diff",
        "notes": "The public facade exposes python-pptx-style slide/shape collections while preserving packages on no-op saves, supporting BytesIO-style open/save targets, and constructing blank presentations from a packaged template without importing python-pptx.",
    },
    {
        "id": "python_api.part_proxy",
        "category": "python_api",
        "capability": "Expose python-pptx-style .part metadata for presentation, slide, layout, shape, action, text, chart, table, and common collection objects",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package blob check",
        "notes": "The facade exposes read-only package part metadata with partname, content_type, blob, part, package, and name behavior for common python-pptx objects without adding a mutation path.",
    },
    {
        "id": "python_api.xml_element_inspection",
        "category": "python_api",
        "capability": "Expose python-pptx-style read-only .element XML inspection for presentation, slide, layout, shape, placeholder, and master objects",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe",
        "notes": "The facade exposes tag, attrib, text, xml, find, findall, xpath, iteration, indexing, and length on copied XML elements for inspection without adding arbitrary XML mutation persistence.",
    },
    {
        "id": "python_api.presentation_slide_size",
        "category": "python_api",
        "capability": "Read and set Presentation.slide_width and Presentation.slide_height",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + XML size check",
        "notes": "The facade mirrors python-pptx slide size reads and EMU range validation, and saves size edits by changing only the presentation XML part.",
    },
    {
        "id": "python_api.core_properties",
        "category": "python_api",
        "capability": "Read and set Presentation.core_properties common document metadata",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + XML metadata check",
        "notes": "The facade mirrors python-pptx for common core properties including title, subject, author, keywords, comments, revision, timestamps, and status metadata while changing only docProps/core.xml.",
    },
    {
        "id": "python_api.slide_metadata",
        "category": "python_api",
        "capability": "Read slide.slide_id, slide.slide_layout, slide.follow_master_background, slide.has_notes_slide, use slides.get(), and set slide.name",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + XML name check",
        "notes": "The facade resolves slide ids and layouts from package relationships, detects notes-slide relationships and inherited backgrounds, and saves slide.name edits by changing only the target slide XML part.",
    },
    {
        "id": "python_api.notes_slide_read",
        "category": "python_api",
        "capability": "Read existing or create missing slide.notes_slide, notes_text_frame, notes shapes/placeholders, and Presentation.notes_master",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package part check + drop-in benchmark",
        "notes": "The facade mirrors python-pptx read access for packages that already contain notes parts and creates missing notes-slide, notes-master, relationship, content-type, and theme parts on first notes access while preserving visible slide text.",
    },
    {
        "id": "python_api.notes_text_setter",
        "category": "python_api",
        "capability": "Set existing notes text, paragraph layout/font, and run formatting via notes_text_frame, paragraph, and run APIs",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + drop-in benchmarks",
        "notes": "Notes text assignment, content-level paragraph/run edits, run font formatting, text-run hyperlinks, paragraph default-font formatting, and paragraph alignment/level/spacing route through a part-scoped edit queue and change only the target notesSlide XML part and notesSlide relationships when hyperlinks change.",
    },
    {
        "id": "python_api.background_fill",
        "category": "python_api",
        "capability": "Read slide, layout, slide-master, and notes-master background elements and fill state; set slide, layout, and slide-master background solid/background fills and foreground colors",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + drop-in benchmark + Open XML validation",
        "notes": "The facade mirrors python-pptx background.element, _element, fill.type, foreground RGB/theme-color/brightness reads, and routes slide, layout, and slide-master background fill.solid(), fill.background(), fill.fore_color.rgb, fill.fore_color.theme_color, and fill.fore_color.brightness through part-scoped edits that change only the target XML part.",
    },
    {
        "id": "python_api.slide_master_metadata",
        "category": "python_api",
        "capability": "Read Presentation.slide_master, Presentation.slide_masters, master slide_layouts, shapes, and placeholders",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package part check",
        "notes": "The facade resolves slide masters and their layouts from package relationships and exposes read-only master placeholder metadata for template inspection workflows.",
    },
    {
        "id": "python_api.placeholder_title_access",
        "category": "python_api",
        "capability": "Read slide.shapes.title, slide.placeholders, and placeholder_format metadata",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + native summary + semantic diff + package diff",
        "notes": "The Rust summary exposes placeholder metadata and the facade resolves title placeholders while routing title text assignment through the native shape-text operation.",
    },
    {
        "id": "python_api.shape_collection_helpers",
        "category": "python_api",
        "capability": "Read slide.shapes.placeholders, shape-tree ph_basename(), and turbo_add_enabled",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe",
        "notes": "The facade mirrors python-pptx shape collection convenience helpers without making turbo_add_enabled affect preservation-oriented id allocation.",
    },
    {
        "id": "python_api.clone_layout_placeholders",
        "category": "python_api",
        "capability": "Clone editable layout placeholders with slide.shapes.clone_layout_placeholders(...) and clone_placeholder(...)",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + native placeholder insertion",
        "notes": "The facade exposes layout shapes/placeholders, skips latent date/footer/slide-number placeholders, and queues native placeholder insertion that changes only the target slide XML.",
    },
    {
        "id": "python_api.shape_text_setter",
        "category": "python_api",
        "capability": "Set shape.text and save through the native Rust mutation engine",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + semantic diff + package diff",
        "notes": "Shape text assignment queues an edit and save applies it through the native set-shape-text operation with a parity probe against python-pptx, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.text_frame_clear",
        "category": "python_api",
        "capability": "Clear shape.text_frame while preserving python-pptx empty-paragraph semantics",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + semantic diff + package diff",
        "notes": "TextFrame.clear() queues a native shape-text edit and keeps one empty paragraph available in memory for follow-up edits before save.",
    },
    {
        "id": "python_api.shape_geometry",
        "category": "python_api",
        "capability": "Read and set shape.left, shape.top, shape.width, and shape.height",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + semantic diff + package diff",
        "notes": "The facade exposes EMU geometry properties and coalesces geometry setters into native Rust geometry batch edits, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.shape_name",
        "category": "python_api",
        "capability": "Read and set shape.name",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML name check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx shape name assignment and patches the target non-visual shape properties while changing only the target slide XML, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.shape_type",
        "category": "python_api",
        "capability": "Read shape.shape_type for common shape classes",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe",
        "notes": 'The facade mirrors python-pptx\'s TEXT_BOX vs AUTO_SHAPE distinction for DrawingML shape elements by honoring p:cNvSpPr txBox="1".',
    },
    {
        "id": "python_api.picture_image_inspection",
        "category": "python_api",
        "capability": "Read shape.image blob, content type, extension, filename, SHA1, pixel size, and DPI for picture shapes",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package blob check",
        "notes": "The facade resolves picture blip relationships to image package parts and exposes an immutable python-pptx-style image value object while non-picture shapes raise AttributeError.",
    },
    {
        "id": "python_api.picture_image_replacement",
        "category": "python_api",
        "capability": "Replace an existing picture image payload while preserving placement and relationships",
        "priority": "P0",
        "status": "supported",
        "oracle": "package blob check + relationship preservation check",
        "notes": "The facade exposes shape.replace_image(...) for saved picture shapes and queues native relationship-preserving media-part replacement so slide XML, geometry, and relationships remain unchanged.",
    },
    {
        "id": "python_api.shape_rotation",
        "category": "python_api",
        "capability": "Read and set shape.rotation",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML rotation check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx clockwise rotation normalization and patches the target shape transform while changing only the target slide XML, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.shape_style_color",
        "category": "python_api",
        "capability": "Set shape.fill.solid(), shape.fill.background(), shape.fill.gradient(), shape.fill.gradient_angle, shape.fill.gradient_stops, shape.fill.patterned(), shape.fill.pattern, shape.fill.fore_color.rgb, shape.fill.back_color.rgb, shape.line.fill.solid(), shape.line.fill.background(), shape.line.fill.patterned(), shape.line.fill.pattern, shape.line.fill.fore_color.rgb, shape.line.fill.back_color.rgb, shape.line.color.rgb, shape.line.width, and shape.line.dash_style",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + Open XML validation",
        "notes": "The facade exposes a python-pptx-style fill and line surface for shape and line solid/background/gradient/patterned fill modes, gradient angle and stop position/RGB edits, preset fill patterns, patterned foreground/background colors, solid RGB styling, line width, and preset line dash styles on existing shape elements, including direct children of top-level group shapes.",
    },
    {
        "id": "python_api.shape_shadow",
        "category": "python_api",
        "capability": "Read and set shape.shadow.inherit",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML effectLst check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx shadow inheritance toggling by adding or removing the target shape's DrawingML effect override while changing only the target slide XML, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.shape_click_hyperlink",
        "category": "python_api",
        "capability": "Read and set shape.click_action.hyperlink.address for external hyperlinks",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + part relationship check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx for adding and clearing external shape hyperlinks by editing the target slide XML and slide relationship part only, including existing direct children of top-level group shapes and notes-slide placeholders through part-scoped notesSlide relationships.",
    },
    {
        "id": "python_api.shape_click_target_slide",
        "category": "python_api",
        "capability": "Read and set shape.click_action.target_slide for internal slide jumps",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + slide relationship check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx for adding and clearing named-slide click actions by editing the target slide XML and slide relationship part only, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.text_frame_paragraph_text",
        "category": "python_api",
        "capability": "Set shape.text_frame.paragraphs[index].text",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + semantic diff + package diff",
        "notes": "The facade exposes paragraph objects and queues paragraph text edits through native Rust paragraph operations, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.text_paragraph_clear",
        "category": "python_api",
        "capability": "Clear shape.text_frame.paragraphs[index] while preserving paragraph properties",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML paragraph check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx Paragraph.clear() by removing runs, line breaks, and fields while preserving paragraph properties and empty paragraph positions, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.text_paragraph_line_break",
        "category": "python_api",
        "capability": "Append a line break with shape.text_frame.paragraphs[index].add_line_break()",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML line-break check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx by inserting DrawingML br elements, exposing paragraph text with vertical-tab line breaks, and keeping run collections limited to real text runs, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.text_paragraph_font",
        "category": "python_api",
        "capability": "Read and set paragraph.font default run properties",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML defRPr check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx paragraph.font for bold, italic, underline, size, name, RGB/theme color, solid/background/patterned/gradient fill, and language_id by patching paragraph default run properties, including existing direct children of top-level group shapes and speaker-notes text frames.",
    },
    {
        "id": "python_api.text_frame_margins",
        "category": "python_api",
        "capability": "Read and set shape.text_frame margin_left/right/top/bottom",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML bodyPr margin check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx text-frame margin defaults and patches the target text-body properties while changing only the target slide XML, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.text_frame_word_wrap",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.word_wrap",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML bodyPr wrap check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx word-wrap True/False/None behavior and patches the target text-body properties while changing only the target slide XML, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.text_frame_vertical_anchor",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.vertical_anchor",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML bodyPr anchor check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx vertical-anchor enum behavior and patches the target text-body properties while changing only the target slide XML, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.text_frame_auto_size",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.auto_size",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML bodyPr autofit check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx auto-size enum behavior and patches the target text-body properties while changing only the target slide XML, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.text_frame_fit_text",
        "category": "python_api",
        "capability": "Fit text with shape.text_frame.fit_text(...)",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML run-property check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx fit_text side effects by setting word-wrap on, auto-size off, and applying the selected font family, size, bold, and italic properties to text runs and paragraph-end run properties.",
    },
    {
        "id": "python_api.text_paragraph_alignment",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.paragraphs[index].alignment",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML paragraph-property check + package diff + Open XML validation",
        "notes": "The facade exposes python-pptx-style paragraph alignment values for existing and appended paragraphs, existing direct children of top-level group shapes, and speaker-notes text frames while changing only the target XML part.",
    },
    {
        "id": "python_api.text_paragraph_level",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.paragraphs[index].level",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML paragraph-property check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx paragraph level values 0 through 8 for existing and appended paragraphs, existing direct children of top-level group shapes, and speaker-notes text frames while changing only the target XML part.",
    },
    {
        "id": "python_api.text_paragraph_spacing",
        "category": "python_api",
        "capability": "Read and set paragraph space_before, space_after, and line_spacing",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML paragraph-property check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx paragraph spacing values, including point spacing and line-spacing multiples, for existing and appended paragraphs, existing direct children of top-level group shapes, and speaker-notes text frames while changing only the target XML part.",
    },
    {
        "id": "python_api.text_frame_run_text",
        "category": "python_api",
        "capability": "Set shape.text_frame.paragraphs[index].runs[index].text",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + semantic diff + package diff",
        "notes": "The facade exposes paragraph run collections and queues run text edits through native Rust batched edit operations while preserving surrounding XML, including existing direct children of top-level group shapes.",
    },
    {
        "id": "python_api.text_run_font_bold",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.paragraphs[index].runs[index].font.bold",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML run-property check + package diff",
        "notes": "The native summary extracts DrawingML bold attributes into the facade, and saves queue native Rust run-property edits for existing, appended, appended-paragraph, and replacement-created runs while preserving unrelated package parts. Existing direct children of top-level group shapes and speaker-notes runs use part-scoped XML edits for bold.",
    },
    {
        "id": "python_api.text_run_font_italic",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.paragraphs[index].runs[index].font.italic",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML run-property check + package diff",
        "notes": "The native summary extracts DrawingML italic attributes into the facade, and saves queue native Rust run-property edits for existing, appended, appended-paragraph, and replacement-created runs while preserving unrelated package parts. Existing direct children of top-level group shapes and speaker-notes runs use part-scoped XML edits for italic.",
    },
    {
        "id": "python_api.text_run_font_underline",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.paragraphs[index].runs[index].font.underline",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML run-property check + package diff",
        "notes": "The native summary maps DrawingML underline values into bool/None facade state, and saves queue native Rust run-property edits for existing, appended, appended-paragraph, and replacement-created runs. Existing direct children of top-level group shapes and speaker-notes runs use part-scoped XML edits for underline.",
    },
    {
        "id": "python_api.text_run_font_size",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.paragraphs[index].runs[index].font.size",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML run-property check + package diff",
        "notes": "The native summary converts DrawingML centipoint sizes to python-pptx-compatible integer values, and saves queue native Rust run-property edits for existing, appended, appended-paragraph, and replacement-created runs. Existing direct children of top-level group shapes and speaker-notes runs use part-scoped XML edits for size.",
    },
    {
        "id": "python_api.text_run_font_name",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.paragraphs[index].runs[index].font.name",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML run-property check + package diff",
        "notes": "The native summary extracts DrawingML latin typefaces into the facade, and saves queue native Rust run-property edits for existing, appended, appended-paragraph, and replacement-created runs. Existing direct children of top-level group shapes and speaker-notes runs use part-scoped XML edits for font name.",
    },
    {
        "id": "python_api.text_run_font_color",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.paragraphs[index].runs[index].font.color rgb/theme values",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML run-property check + package diff + Open XML validation",
        "notes": "The facade exposes python-pptx-style run font RGB and theme color for existing, appended, appended-paragraph, replacement-created runs, existing direct children of top-level group shapes, and speaker-notes runs while changing only the target XML part.",
    },
    {
        "id": "python_api.text_run_font_language_id",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.paragraphs[index].runs[index].font.language_id",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML run-property check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx language_id enum/None behavior by setting or removing the DrawingML lang attribute on existing runs, existing direct children of top-level group shapes, and speaker-notes runs while changing only the target XML part.",
    },
    {
        "id": "python_api.text_run_font_fill",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.paragraphs[index].runs[index].font.fill",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML run-property check + package diff + Open XML validation",
        "notes": "The facade supports python-pptx-style run font fill.solid(), fill.background(), fill.patterned(), fill.gradient(), fill.type, pattern foreground/background RGB, gradient angle/stop edits, and fill.fore_color.rgb on existing runs, existing direct children of top-level group shapes, and speaker-notes runs while changing only the target XML part.",
    },
    {
        "id": "python_api.text_run_hyperlink",
        "category": "python_api",
        "capability": "Read and set shape.text_frame.paragraphs[index].runs[index].hyperlink.address for external hyperlinks",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + part relationship check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx for adding and clearing external text-run hyperlinks by editing the target slide XML and relationship part only, including existing direct children of top-level group shapes and speaker-notes text runs through part-scoped notesSlide relationships.",
    },
    {
        "id": "python_api.text_frame_add_paragraph_run",
        "category": "python_api",
        "capability": "Append text with shape.text_frame.add_paragraph() and paragraph.add_run()",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + semantic diff + package diff",
        "notes": "The facade appends paragraphs and runs through native batched edit operations that preserve existing text body XML; appended paragraphs can receive paragraph and run formatting edits before save.",
    },
    {
        "id": "python_api.slide_add_from_layout",
        "category": "python_api",
        "capability": "Add a slide from prs.slide_layouts[index] through prs.slides.add_slide(layout)",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + semantic diff + package diff",
        "notes": "The facade exposes slide_layouts and queues add_slide edits through the native Rust add-slide operation.",
    },
    {
        "id": "python_api.add_picture",
        "category": "python_api",
        "capability": "Add a picture with slide.shapes.add_picture(...) and group.shapes.add_picture(...)",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + semantic diff + package diff",
        "notes": "The facade accepts path and file-like PNG, JPEG, GIF, BMP, and TIFF image inputs with explicit, native, or proportionally inferred bounds, normalizes JPEG/TIFF part extensions like python-pptx, and queues slide-level, top-level group, and nested-group image insertion through native Rust image operations. Slide-level, top-level group, and nested-group additions expose python-pptx-style shape_id values before save.",
    },
    {
        "id": "python_api.add_movie",
        "category": "python_api",
        "capability": "Add a movie with slide.shapes.add_movie(movie, left, top, width, height, poster_frame_image=None, mime_type='video/unknown')",
        "priority": "P1",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + Open XML validation",
        "notes": "The facade exposes python-pptx-style add_movie for path and file-like movie/poster inputs, including PNG/JPEG/GIF/BMP/TIFF poster frames, returns a MEDIA shape with a python-pptx-style shape_id before save, and queues the native movie writer for save.",
    },
    {
        "id": "python_api.add_ole_object",
        "category": "python_api",
        "capability": "Add an embedded object with slide.shapes.add_ole_object(...) or group.shapes.add_ole_object(...)",
        "priority": "P1",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + Open XML validation",
        "notes": "The facade exposes python-pptx-style add_ole_object for path and file-like embedded object/icon inputs, including PNG/JPEG/GIF/BMP/TIFF icons, returns an EMBEDDED_OLE_OBJECT shape with a python-pptx-style shape_id before save at slide, top-level group, and nested-group scope, exposes shape.ole_format read metadata, and queues native OLE insertion.",
    },
    {
        "id": "python_api.add_connector",
        "category": "python_api",
        "capability": "Add connectors with slide.shapes.add_connector(...) and group.shapes.add_connector(...), read endpoint coordinates, and persist begin_connect/end_connect attachments",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML connector check + package diff + Open XML validation",
        "notes": "The facade supports straight, elbow, and curve connector presets at slide level, inside top-level groups, and inside nested groups through native connector-add operations while changing only the target slide XML. Existing and newly added connectors expose python-pptx-style shape_id, begin_x, begin_y, end_x, and end_y reads before save. Slide-level connector begin_connect/end_connect attachments to saved or newly added shapes, including text boxes and pictures, persist connection metadata and endpoint transforms with python-pptx parity probes.",
    },
    {
        "id": "python_api.connector_line_style",
        "category": "python_api",
        "capability": "Read and set connector line color, width, and dash style",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML line-style check + package diff + Open XML validation",
        "notes": "The facade applies python-pptx-style line color, width, and dash edits to existing connector elements while changing only the target slide XML.",
    },
    {
        "id": "python_api.picture_crop",
        "category": "python_api",
        "capability": "Read and set picture crop_left, crop_right, crop_top, and crop_bottom",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML srcRect check + package diff + Open XML validation",
        "notes": "The facade supports python-pptx-style picture crop fractions for existing picture elements while changing only the target slide XML.",
    },
    {
        "id": "python_api.add_textbox",
        "category": "python_api",
        "capability": "Add a text box with slide.shapes.add_textbox(...) and group.shapes.add_textbox(...)",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + semantic diff + package diff",
        "notes": "The facade queues slide-level, existing-group, newly created group, and nested-group text box insertion through native Rust operations, exposes python-pptx-style shape_id values before save, and allows immediate text assignment before save.",
    },
    {
        "id": "python_api.add_group_shape",
        "category": "python_api",
        "capability": "Add group shapes with slide.shapes.add_group_shape(...) or group.shapes.add_group_shape()",
        "priority": "P1",
        "status": "supported",
        "oracle": "python-pptx parity probe + semantic diff + package diff + Open XML validation",
        "notes": "The facade queues empty slide-level and nested group-shape insertion through native Rust operations. It also supports python-pptx-style grouping of existing top-level slide shapes with slide.shapes.add_group_shape(existing_shapes), existing direct children with group.shapes.add_group_shape(existing_children), and existing direct children inside nested or deeper nested groups, changing only the target slide XML and preserving the argument order. New groups expose python-pptx-style shape_id values before save, and text boxes, basic preset shapes, connectors, pictures, charts, OLE objects, and freeforms can be added inside nested or deeper nested groups before save.",
    },
    {
        "id": "python_api.build_freeform",
        "category": "python_api",
        "capability": "Build a freeform shape with slide.shapes.build_freeform(...) or group.shapes.build_freeform(...).convert_to_shape()",
        "priority": "P1",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML custom-geometry check + semantic diff + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx local-coordinate line segments, move-to operations, close operations, origin offsets, and shape_id availability before save, then queues native Rust slide-level, top-level group, nested-group, or deeper nested-group freeform insertion that changes only the target slide XML.",
    },
    {
        "id": "python_api.add_shape_basic",
        "category": "python_api",
        "capability": "Add common preset shapes with slide.shapes.add_shape(...) and group.shapes.add_shape(...)",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML preset check + semantic diff + package diff",
        "notes": "The facade supports common geometry presets including rectangles, ovals, triangles, diamonds, arrows, chevrons, stars, clouds, and other frequent diagram shapes through native Rust auto-shape operations at slide level, inside top-level group shapes, and inside nested group shapes.",
    },
    {
        "id": "python_api.auto_shape_type",
        "category": "python_api",
        "capability": "Read shape.auto_shape_type for common preset autoshapes and picture-shape rectangle parity",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML preset check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx auto_shape_type for supported preset autoshapes, returns RECTANGLE for picture shapes like python-pptx, and raises for text boxes/non-autoshapes.",
    },
    {
        "id": "python_api.shape_adjustments",
        "category": "python_api",
        "capability": "Read and set shape.adjustments for supported preset autoshapes",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML guide check + package diff + benchmark coverage + Open XML validation",
        "notes": "The facade mirrors python-pptx adjustment collections for supported preset autoshapes such as rounded rectangles at slide level and inside grouped shapes, writing DrawingML adjustment guides while changing only the target slide XML.",
    },
    {
        "id": "python_api.shape_line_xml_helpers",
        "category": "python_api",
        "capability": "Read shape.ln and create a line XML element with shape.get_or_add_ln()",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML line check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx's low-level line element helpers for shape, picture, connector, and freeform elements and persists get_or_add_ln() by changing only the target slide XML.",
    },
    {
        "id": "python_api.table_cell_text",
        "category": "python_api",
        "capability": "Read table dimensions, set row/column dimensions, and set table.cell(row, col).text",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + semantic diff + package diff + benchmark profile",
        "notes": "The facade exposes shape.has_table, shape.table, rows, columns, queued row/column dimension edits, and queued cell text edits through the native Rust table-cell operation.",
    },
    {
        "id": "python_api.table_cell_text_frame",
        "category": "python_api",
        "capability": "Read and set table cell text_frame text, paragraph formatting, margins, fit, and anchors",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + surface ratchet",
        "notes": "The facade mirrors python-pptx table.cell(row, col).text_frame text, paragraphs, add_paragraph(), clear(), paragraph add_line_break(), paragraph run text/add_run()/font formatting/hyperlinks, paragraph alignment/level/spacing/default-font formatting including language_id, word_wrap, auto_size, margins, and vertical-anchor properties while changing only the target slide XML plus slide relationships when hyperlinks change. fit_text() writes conservative fit XML for table cells where python-pptx currently cannot compute _Cell extents.",
    },
    {
        "id": "python_api.table_cell_fill",
        "category": "python_api",
        "capability": "Read and set table.cell(row, col).fill solid, gradient, pattern, and background fills",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + surface ratchet + benchmark coverage + Open XML validation",
        "notes": "The facade mirrors python-pptx table cell fill.solid(), fill.background(), fill.gradient(), gradient_angle, gradient_stops color/position helpers, fill.fore_color RGB/theme colors, and patterned foreground/background RGB/theme colors by editing only the target slide XML cell properties.",
    },
    {
        "id": "python_api.table_cell_merge",
        "category": "python_api",
        "capability": "Merge and split table cells with span metadata",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + surface ratchet + Open XML validation",
        "notes": "The facade mirrors python-pptx table cell merge(), split(), is_merge_origin, is_spanned, span_width, and span_height by editing only table-cell span attributes and text bodies in the target slide XML.",
    },
    {
        "id": "python_api.table_style_flags",
        "category": "python_api",
        "capability": "Read and set table style flags and iterate cells",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + surface ratchet",
        "notes": "The facade mirrors python-pptx table.first_row, first_col, last_row, last_col, horz_banding, vert_banding, iter_cells(), and notify_* no-op hooks while changing only the target slide XML for flag edits.",
    },
    {
        "id": "python_api.add_table",
        "category": "python_api",
        "capability": "Add a table with slide.shapes.add_table(rows, cols, left, top, width, height)",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + semantic diff + package diff",
        "notes": "The facade queues table insertion through the native Rust add-table operation and allows cell edits before save.",
    },
    {
        "id": "python_api.add_chart",
        "category": "python_api",
        "capability": "Add a chart with slide.shapes.add_chart(...) and group.shapes.add_chart(...)",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + chart metadata check + package diff + Open XML validation",
        "notes": "The facade adds python-pptx-style category charts, XY scatter charts, bubble charts, and 3D bubble charts on slides, top-level group shapes, and nested group shapes by transplanting packaged chart templates, an embedded workbook, slide relationship, and content-type entries into the original package without importing python-pptx at save time. Chart additions accept python-pptx-compatible no-series and empty-series data, plus sparse/mismatched and hierarchical category chart data. Chart graphic frames expose python-pptx-style shape_id values before save and shape.chart_part metadata for read parity.",
    },
    {
        "id": "python_api.chart_inspection",
        "category": "python_api",
        "capability": "Inspect chart.element, chart.plots, chart.series/points, chart.chart_style, chart fonts, chart formats, axis gridlines, and tick labels",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + chart-read benchmark + package diff",
        "notes": "The facade mirrors python-pptx chart XML inspection, plot/category/series reads, series index/format/data-label proxies, point format/data-label/marker proxies, point data-label text-frame paragraph/run/hyperlink/fit_text surface, chart_style reads/writes, chart_title.element/has_text_frame metadata, writable chart/axis title formats, writable axis and major-gridline line formats, writable chart font language_id, major gridline proxies, tick-label number-format reads, tick-label font language_id, and category-axis type metadata while isolating style edits to the chart XML part.",
    },
    {
        "id": "python_api.chart_replace_data",
        "category": "python_api",
        "capability": "Replace chart data with shape.chart.replace_data(CategoryChartData/XyChartData/BubbleChartData)",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx for simple, date-category, sparse, and hierarchical category data, XY scatter, and bubble chart data replacement plus series-count changes and uneven XY/bubble point counts, while updating both chart metadata reads and the embedded workbook payload. No-series replacement is parity-covered, but zero-plot outputs can fail strict Open XML validation just like python-pptx, so Open XML benchmark evidence uses empty-series and sparse replacement cases.",
    },
    {
        "id": "python_api.chart_title_text",
        "category": "python_api",
        "capability": "Read and set chart.has_title plus chart.chart_title text-frame, fit_text, rich text, and format fill/line styling",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML title rich-text check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx chart title creation/removal, text_frame text, margins, word_wrap, vertical_anchor, auto_size, fit_text() conservative XML, paragraphs.add_paragraph(), paragraph.text, paragraph alignment/level/spacing/default-font formatting including language_id and rich font fill, runs.add_run(), run.text, common run font formatting including language_id/rich font fill, and chart_title.format fill plus patterned line-fill styling while changing only the target chart XML part.",
    },
    {
        "id": "python_api.chart_legend",
        "category": "python_api",
        "capability": "Read and set chart.has_legend, chart.legend position/layout flags, and legend font formatting",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML legend check + package diff + benchmark + Open XML validation",
        "notes": "The facade mirrors python-pptx chart legend creation/removal, legend position/layout flags, and common legend font formatting including rich gradient fills while changing only the target chart XML part.",
    },
    {
        "id": "python_api.chart_axis_title",
        "category": "python_api",
        "capability": "Read and set category_axis/value_axis title text-frame flow, fit_text, paragraph formatting, runs, and run font formatting",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + XML axis-title rich-text check + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx category/value axis title creation/removal, text_frame text, margins, word_wrap, vertical_anchor, auto_size, fit_text() conservative XML, paragraphs.add_paragraph(), paragraph.text, paragraph alignment/level/spacing/default-font formatting including language_id and rich font fill, runs.add_run(), run.text, and common run font formatting including language_id and rich font fill while changing only the target chart XML part.",
    },
    {
        "id": "python_api.chart_axis_properties",
        "category": "python_api",
        "capability": "Read and set common category_axis/value_axis visibility, gridline, tick-label, order, scale, unit, and crossing properties",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + benchmark + Open XML validation",
        "notes": "The facade mirrors python-pptx for visible, axis line formatting, major-gridline line formatting, major/minor gridline flags, major/minor tick marks, tick-label position, tick-label number format/source linkage/font size/font language_id/category offset, reverse order, min/max scale, value-axis major/minor units, and value-axis crossing controls while changing only the target chart XML part.",
    },
    {
        "id": "python_api.chart_data_labels",
        "category": "python_api",
        "capability": "Read, add, configure, and remove plot and point data labels",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + benchmark + Open XML validation",
        "notes": "The facade mirrors python-pptx plot.has_data_labels and plot.data_labels for value/category/series/percentage/legend-key visibility, label position, number format, source linkage, and rich default font formatting including language_id, gradient fills, and patterned fills, plus series.data_labels and point.data_label default fonts, text-frame toggles, paragraph layout/default rich font fills/line breaks, run font language_id/rich fill, and fit_text() conservative XML while changing only the target chart XML part.",
    },
    {
        "id": "python_api.chart_point_formatting",
        "category": "python_api",
        "capability": "Set chart series, per-point, and point-marker fill modes/colors, line formatting, marker style, and marker size",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + benchmark + Open XML validation",
        "notes": "The facade mirrors python-pptx series/point/point-marker format.fill.solid(), format.fill.background(), format.fill.patterned(), format.fill.gradient(), fill pattern, gradient angle/stops, foreground/background RGB, format.line.fill.solid(), format.line.fill.background(), format.line.fill.patterned(), line fill pattern foreground/background RGB, format.line.fill.fore_color.rgb, format.line.color.rgb, format.line.width, format.line.dash_style, point.marker.style, and point.marker.size for category charts while changing only the target chart XML part.",
    },
    {
        "id": "python_api.chart_plot_properties",
        "category": "python_api",
        "capability": "Read and set chart plot properties such as vary_by_categories, gap_width, and overlap",
        "priority": "P0",
        "status": "supported",
        "oracle": "python-pptx parity probe + package diff + Open XML validation",
        "notes": "The facade mirrors python-pptx plot.vary_by_categories, gap_width, and overlap semantics, including default behavior when plot spacing XML is absent, while changing only the target chart XML part.",
    },
]
